name: speech-command-rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - librosa
  - pytorch
  - jupyter
  - pip:
      - -r requirements.txt
